# 반복문 2- for

## 안녕하세요? 5번 출력하기

In [ ]:
for i in range(5):
  print("안녕하세요")


##for문의 종류
###range(종료값)

###range(시작값, 종료값)

###range(시작값, 종료값, 증가_감소)

In [1]:
for i in range(10,20,2):
  print(i, end=" ")

10 12 14 16 18

### 1) 1~10 정수 합계 구하기
실행결과:

1~10의 합계 : 55

In [7]:
sum = 1;
for i in range(1,10):
  sum += i+1
print(sum)

55

### 2) 500~1000의 수 중에서 3의 배수 합계 구하기
실행결과:

501

504

507

...

993

996

999

합계 : 125250

In [12]:
total = 0
for i in range(500, 1000):
    if i % 3 == 0:
        total += i
        print(total)

501
1005
1512
2022
2535
3051
3570
4092
4617
5145
5676
6210
6747
7287
7830
8376
8925
9477
10032
10590
11151
11715
12282
12852
13425
14001
14580
15162
15747
16335
16926
17520
18117
18717
19320
19926
20535
21147
21762
22380
23001
23625
24252
24882
25515
26151
26790
27432
28077
28725
29376
30030
30687
31347
32010
32676
33345
34017
34692
35370
36051
36735
37422
38112
38805
39501
40200
40902
41607
42315
43026
43740
44457
45177
45900
46626
47355
48087
48822
49560
50301
51045
51792
52542
53295
54051
54810
55572
56337
57105
57876
58650
59427
60207
60990
61776
62565
63357
64152
64950
65751
66555
67362
68172
68985
69801
70620
71442
72267
73095
73926
74760
75597
76437
77280
78126
78975
79827
80682
81540
82401
83265
84132
85002
85875
86751
87630
88512
89397
90285
91176
92070
92967
93867
94770
95676
96585
97497
98412
99330
100251
101175
102102
103032
103965
104901
105840
106782
107727
108675
109626
110580
111537
112497
113460
114426
115395
116367
117342
118320
119301
120285
121272
122262
123255
124251
125250
125250

###3) 1~1000 의 자연수 중에서 5의 배수가 아닌 수의 합계 구하기
실행결과:

합계 : 400000

In [13]:
total = 0
for i in range(1, 1000):
    if i % 5 != 0:
        total += i
print(total)

400000

###4)문장을 세로로 출력하기


실행결과:

한글(또는 영어) 문장을  입력하세요 : 안녕하세요

안

녕

하

세

요

In [ ]:
sentence = input("한글(또는 영어) 문장을 입력하세요 : ")

for i in sentence:
  print(i)

한글(또는 영어) 문장을 입력하세요 : 안녕하세요
안
녕
하
세
요

###5)전화번호에서 하이픈(-) 제거하기

실행결과:

하이픈(-)을 포함하여 전화번호를 입력하세요 : 010-555-1234

0105551234

In [14]:
phone_number = input("전화번호 : ")
new_number = phone_number.replace("-", "")
print(new_number)

01012345678

###6)공백 대신 밑줄(_) 삽입하기

실행결과:

문장을 입력하세요 : 안녕 친구야 만나서 반가워

안녕_친구야_만나서_반가워

In [15]:
string = "안녕 친구야 만나서 반가워"
new_string = string.replace(" ", "_")
print(new_string)

안녕_친구야_만나서_반가워

###7) 1~10 까지 리터 갤런 온스 리스트 만들기

공식

갤런 = 리터 x 0.264
온스 = 리터 x 33.814

실행결과:

------------------------------
    리터     갤런     온스
------------------------------
    1.00     0.26    33.81
    3.00     0.79   101.44
    5.00     1.32   169.07
    7.00     1.85   236.70
    9.00     2.38   304.33
------------------------------

In [16]:
print("------------------------------")
print("   리터     갤런     온스")
print("------------------------------")

for i in range(1, 11):
    liter = i
    gallon = liter * 0.264
    ounce = liter * 33.814
    print("{:8.2f}{:8.2f}{:8.2f}".format(liter, gallon, ounce))

print("------------------------------")

------------------------------
   리터     갤런     온스
------------------------------
    1.00    0.26   33.81
    2.00    0.53   67.63
    3.00    0.79  101.44
    4.00    1.06  135.26
    5.00    1.32  169.07
    6.00    1.58  202.88
    7.00    1.85  236.70
    8.00    2.11  270.51
    9.00    2.38  304.33
   10.00    2.64  338.14
------------------------------